application: udacity-ac-blog
version: 2
runtime: python27
api_version: 1
threadsafe: true


libraries:
- name: jinja2
  version: latest

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  script: blog.application
